name: WhereTo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    


 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_neumorphic: ^ 3.0.1
  curved_navigation_bar: ^0.3.3
  shared_preferences: ^0.5.7+3
  responsive_framework: ^0.0.7
  rxdart: ^0.24.1
  flutter_bloc: ^4.0.0
  carousel_slider: ^1.3.0
  solid_bottom_sheet: ^0.1.9
  google_fonts: ^0.3.10
  momentum: ^1.2.7
  stepper_counter_swipe: ^0.0.5
  flutter_counter: ^1.0.3
  mobx: ^1.2.1+1
  build_runner: ^1.10.0
  provider: ^4.1.3
  argon_buttons_flutter: ^1.0.2
  badges: ^1.1.1
  onesignal_flutter: ^2.6.0
  workmanager: ^0.2.3
  url_launcher: ^5.5.0
  geocoder: ^0.2.1
  geolocation: ^1.1.2
  location: ^3.0.2
  geodesy: ^0.3.2
  draggable_fab: ^0.1.1
  slide_popup_dialog: ^0.0.2
  neumorphic: ^0.3.2
  modal_bottom_sheet: ^0.2.0+1
  # dio: ^3.0.9
  geolocator: ^5.3.2+2
  ntp: ^1.0.7
  google_maps_flutter: ^0.5.30
  awesome_dialog: ^1.1.3
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.0
  cloudinary_client: ^0.0.9
  ticketview: ^1.0.0
  cloudinary_public: ^0.3.3
  flutter_staggered_grid_view: ^0.3.2
  transparent_image: ^1.0.0
  md2_tab_indicator: ^1.0.2
  get: ^3.4.6
  connectivity: ^0.4.9+2
  rx_shared_preferences: ^1.3.0
  progress_dialog: ^1.2.4
  dropdown_banner: ^1.4.0
  platform_alert_dialog: ^1.0.0+2
  photo_view: ^0.10.2
  flushbar: ^1.10.4
  date_range_picker: ^1.0.6
  extended_image: ^1.1.1
  animations: ^1.1.2
  flutter_spinkit: ^4.1.2
  introduction_screen: ^1.0.7
  # syncfusion_flutter_datepicker: ^18.2.55-beta
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec




# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
  - asset/img/deliveryProcess.png
  - asset/img/doneprocess.png
  - asset/img/emptycart.png
  - asset/img/nosearch.png
  - asset/img/notifempty.png
  - asset/img/ongoing.png
  - asset/img/penalty.png
  - asset/img/heartIcon.jpg
  - asset/img/logo.png
  - asset/img/menuBuyinu.png



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/font/OpenSans-Regular.ttf

    - family: Brandon_Grotesque
      fonts: 
      - asset: asset/font/brandon-grotesque-black-58a8a3e824392.otf
         
    - family: Brandon_italic
      fonts: 
      - asset: asset/font/brandon-grotesque-bold-italic-58a8a48221563.otf
      
    - family: Brandon_Grotesque_regular_italic
      fonts: 
      - asset: asset/font/brandon-grotesque-regular-italic-58a8a456c4724.otf 
    
    - family: Brandon_Grotesque_medium
      fonts: 
      - asset: asset/font/brandon-grotesque-medium-italic-58a8a3c40866a.otf

    - family: Brandon_Grotesque_light
      fonts:  
      - asset: asset/font/brandon-grotesque-light-58a8a4b38001d.otf
      
    - family: Gilroy-ExtraBold
      fonts:
      - asset: asset/font/Radomir Tinkov - Gilroy-ExtraBold.otf
      
    - family: Gilroy-light
      fonts:
      - asset: asset/font/Radomir Tinkov - Gilroy-Light.otf      
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
